#!/usr/bin/env python3

from jinja2 import Environment, FileSystemLoader, Template
file_loader = FileSystemLoader('templates')
env = Environment(loader=file_loader)
template = env.get_template('fsbano.j2')
print (template.render(name='Marcelo Santos', friend='Jaqueline Ribeiro')) 
